baseURL: "https://fffzlfk.github.io"
title: fffzlfk's Blog
paginate: 5
theme: ["hugo-notice", "PaperMod"]

enableRobotsTXT: true
buildDrafts: false
buildFuture: false
buildExpired: false
enableEmoji: true

minify:
  disableXML: true
  minifyOutput: true

params:
  # env: production # to enable google analytics, opengraph, twitter-cards and schema.
  title: fffzlfk's Blog
  description: "Thinking will not overcome fear but action will."
  keywords: [Blog, Portfolio, PaperMod]
  author: fffzlfk
  # author: ["Me", "You"] # multiple authors
  DateFormat: "January 2, 2006"
  defaultTheme: auto # dark, light
  disableThemeToggle: false

  ShowReadingTime: true
  ShowShareButtons: false
  ShowPostNavLinks: true
  ShowBreadCrumbs: true
  ShowCodeCopyButtons: true
  disableSpecial1stPost: false
  disableScrollToTop: false
  comments: true
  hidemeta: false
  hideSummary: false
  showtoc: true
  tocopen: false

  assets:
    # disableFingerprinting: true
    favicon: "/favicon.ico"
    favicon16x16: "/favicon-16x16.png"
    favicon32x32: "/favicon-32x32.png"
    apple_touch_icon: "/apple_touch_icon.png"
    safari_pinned_tab: "/favicon.ico"
    disableHLJS: false

  label:
    text: "fffzlfk's Blog"
    icon: /android-chrome-512x512.png
    iconHeight: 35

  # profile-mode
  profileMode:
    enabled: false # needs to be explicitly set
    title: fffzlfk's Blog
    subtitle: "Thinking will not overcome fear but action will."
    imageUrl: "https://avatars.githubusercontent.com/u/44939690?v=4"
    imageWidth: 120
    imageHeight: 120
    imageTitle: my image
    buttons:
      - name: Posts
        url: posts
      - name: Tags
        url: tags

  # home-info mode
  homeInfoParams:
    enabled: true
    Title: "Hi there \U0001F44B"
    Content: Thinking will not overcome fear but action will.
    Avatar: "https://avatars.githubusercontent.com/u/44939690?v=4"
    
  socialIcons:
    - name: github
      url: "https://github.com/fffzlfk"
    - name: twitter
      url: "https://twitter.com/fffzlfk"
    - name: instagram
      url: "https://instagram.com/fffzlfk"
    - name: bilibili
      url: "https://space.bilibili.com/82433974"
    - name: gitlab
      url: "https://gitlab.com/fffzlfk"
    - name: stackoverflow
      url: "https://stackoverflow.com/users/11393838/zlfk-fffk"
    - name: buymeacoffee
      url: "https://buymeacoffee.com/fffzlfk"

  analytics:
    # google:
      # SiteVerificationTag: "UA-147061302-1"
    # bing:
    #   SiteVerificationTag: "XYZabc"
    # yandex:
    #   SiteVerificationTag: "XYZabc"

  cover:
    hidden: true # hide everywhere but not in structured data
    hiddenInList: true # hide on list pages and home
    hiddenInSingle: true # hide on single page

  editPost:
    URL: "https://github.com/fffzlfk/fffzlfk.github.io/blob/master/content"
    Text: "Suggest Changes" # edit text
    appendFilePath: true # to append file path to Edit link

  # for search
  # https://fusejs.io/api/options.html
  fuseOpts:
    isCaseSensitive: false
    shouldSort: true
    location: 0
    distance: 1000
    threshold: 0.4
    minMatchCharLength: 0
    keys: ["title", "permalink", "summary", "content"]

  # giscus:
  #   repo: "fffzlfk/fffzlfk.github.io"
  #   repo_id: "R_kgDOG4ERGw"
  #   category: "General"
  #   category_id: "DIC_kwDOG4ERG84CBP5s"
  #   mapping: "pathname"
  #   reactions-enabled: "1"
  #   emit-metadata: "0"
  #   lang: "zh-CN"
  #   theme: "light"
  
disqusShortname: "https-fffzlfk-github-io"

menu:
  main:
    - name: Archive
      url: archives
      weight: 10
    - name: Tags
      url: /tags/
      weight: 5
    - name: Search
      url: search/
      weight: 30
    - name: About
      url: about/
      weight: 20
    - name: GitHub
      url: https://github.com/fffzlfk
      weight: 5
    - name: Travellings
      url: https://travellings.link
      weight: 30
# Read: https://github.com/adityatelange/hugo-PaperMod/wiki/FAQs#using-hugos-syntax-highlighter-chroma
# pygmentsUseClasses: true
markup:
    # highlight:
    #     # anchorLineNos: true
    #     codeFences: true
    #     guessSyntax: true
    #     lineNos: true
    #     style: monokai

outputs:
    home:
        - HTML
        - RSS
        - JSON # is necessary
